version: '3'

services:
    airclass:
        image: airclass:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: airclass
        hostname: airclass
        volumes:
            - .env:/usr/src/app/.env:ro
        restart: unless-stopped
        ports:
            - '3000:3000'
# Uncomment below, remove "ports:" section above and configure labels as
# needed for LetsEncrypt TLS certificates with Traefik.
# See https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/
#   expose:
#     - 3000
#   labels:
#     - "traefik.enable=true"
#     - "traefik.http.routers.airclass.rule=Host(`airclass.example.com`)"
#     - "traefik.http.routers.airclass.entrypoints=websecure"
#     - "traefik.http.routers.airclass.tls.certresolver=myresolver"
#     - "traefik.http.services.airclass.loadbalancer.server.port=3000"
